# Generated by Django 5.2.6 on 2025-11-19 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet_advisor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
