# Generated by Django 5.2.6 on 2025-11-19 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diet_advisor', '0002_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=30)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('activity_level', models.CharField(choices=[('sedentary', 'sedentary'), ('lightly active', 'lightly active'), ('moderatively active', 'moderatively active'), ('very active', 'very active')], max_length=30)),
                ('goal', models.CharField(choices=[('lose_weight', 'lose_weight'), ('gain_weight', 'gain_weight'), ('maintain_weight', 'maintain_weight')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
