# Generated by Django 5.2.8 on 2025-11-27 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet_advisor', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
