# Generated by Django 5.2.8 on 2025-11-27 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diet_advisor', '0004_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=30)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('activity_level', models.CharField(choices=[('sedentary', 'sedentary'), ('lightly active', 'lightly active'), ('moderatively active', 'moderatively active'), ('very active', 'very active')], max_length=30)),
                ('goal', models.CharField(choices=[('lose_weight', 'lose_weight'), ('gain_weight', 'gain_weight'), ('maintain_weight', 'maintain_weight')], max_length=100)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('bmr', models.FloatField(blank=True, null=True)),
                ('calories_needed', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Foodlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('calories_detected', models.CharField(max_length=100)),
                ('food_image', models.ImageField(upload_to='foodimage/')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('calories_status', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('UserProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet_advisor.userprofile')),
            ],
        ),
    ]
