# Generated by Django 5.2.8 on 2025-11-27 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet_advisor', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foodlog',
        ),
    ]
