# Generated by Django 5.2.8 on 2025-12-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_advisor', '0008_premiumorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'sedentary'), ('lightly_active', 'lightly active'), ('moderatively_active', 'moderatively active'), ('very_active', 'very active')], max_length=30),
        ),
    ]
