# Generated by Django 5.2.8 on 2025-12-30 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet_advisor', '0009_alter_userprofile_activity_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Foodlog',
        ),
        migrations.DeleteModel(
            name='PremiumOrder',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
